[colors.primary]
foreground = "#d3c6aa"
background = "#2d353b"

[colors.cursor]
text = "#2d353b"
cursor = "#d3c6aa"

[colors.selection]
text = "#d3c6aa"
background = "#414b51"

[colors.normal]
black = "#343f44"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#859289"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
